export type Project = {
  slug?: string;
  order?: number;
  no: string;
  name: string;
  location: string;
  year: string;
  category: string;
  /** the architect / design studio who authored the design — always credited */
  architect: string;
  developer?: string;
  typology: string;
  discipline?: "Exterior" | "Interior";
  status: string;
  size: string;
  desc: string;
  desc2: string;
  featured: boolean;
  /** placeholder render gradient keys (s1..s6) until real imagery is dropped in */
  scene: string;
  sceneB: string;
  /** CMS image URLs; the scene gradients remain as graceful fallbacks */
  mainImageUrl?: string;
  secondaryImageUrl?: string;
  tertiaryImageUrl?: string;
  quaternaryImageUrl?: string;
  additionalImageUrls?: string[];
  imageAlt?: string;
  align: "left" | "right" | "full";
  /** grid tile size for the works grid */
  span: "tall" | "wide" | "std";
};

const PROJECT_CATALOG: Project[] = [
  {
    slug: "megaverse",
    order: 0,
    no: "01",
    name: "Megaverse",
    location: "Pune, India",
    year: "2025",
    category: "Commercial",
    architect: "AB Architects",
    developer: "Jeswani Associates",
    typology: "Commercial",
    discipline: "Exterior",
    status: "Completed",
    size: "Multi-tower development",
    desc: "A vertical neighbourhood built around life at the ground plane. Megaverse brings together contemporary residential towers, landscape, sport and social infrastructure around a vibrant central community podium.",
    desc2: "Megaverse is a contemporary high-rise residential development conceived around a central landscape and recreation podium. Multiple residential towers frame an active communal environment containing sports courts, swimming facilities, landscaped gardens, pedestrian trails, play areas and social spaces. The architecture combines repetitive modular façades with recessed balconies and strong horizontal lines, creating depth and rhythm across the residential elevations. At ground and podium level, the scale shifts toward the pedestrian, where landscape, recreation and shaded gathering spaces create a more intimate community environment. The masterplan prioritizes the shared experience of residents, positioning recreational spaces at the centre while keeping vehicular circulation predominantly along the site's perimeter. Surrounded by dense greenery, Megaverse explores how high-density urban living can coexist with generous communal landscapes and an active outdoor lifestyle.",
    featured: true,
    scene: "s5",
    sceneB: "s1",
    mainImageUrl: "/project-images/megaverse/masterplan.webp",
    secondaryImageUrl: "/project-images/megaverse/architecture.webp",
    tertiaryImageUrl: "/project-images/megaverse/experience.webp",
    imageAlt: "Aerial masterplan view of Megaverse residential towers surrounding a central recreation podium",
    align: "full",
    span: "wide",
  },
  {
    slug: "private-residence",
    order: 1,
    no: "02",
    name: "Private Residence",
    location: "Mumbai, India",
    year: "2025",
    category: "Residential · Interiors",
    architect: "Sareen Shaikalgar",
    typology: "Residential",
    discipline: "Interior",
    status: "Completed",
    size: "Private residence",
    desc: "A warm, contemporary interior shaped by classical wall mouldings, curved forms, soft neutral finishes and rich timber accents.",
    desc2: "Private Residence is a warm, contemporary interior shaped by classical wall mouldings, curved forms, soft neutral finishes and rich timber accents. Layered lighting, sculptural furniture, patterned textiles and subtle Indian details bring depth and personality to the compact living and dining spaces.",
    featured: true,
    scene: "s4",
    sceneB: "s2",
    mainImageUrl: "/project-images/private-residence/sofa-wall.webp",
    secondaryImageUrl: "/project-images/private-residence/diagonal-view.webp",
    tertiaryImageUrl: "/project-images/private-residence/dining-wall.webp",
    quaternaryImageUrl: "/project-images/private-residence/tv-wall.webp",
    imageAlt: "Warm contemporary living room with classical wall mouldings and sculptural furniture",
    align: "left",
    span: "std",
  },
  {
    slug: "rowhouse-community",
    order: 2,
    no: "03",
    name: "Rowhouse Community",
    location: "Pune, India",
    year: "2025",
    category: "Residential Architecture",
    architect: "Cubix",
    developer: "Bhandari Associates",
    typology: "Residential",
    discipline: "Exterior",
    status: "Completed",
    size: "Rowhouse community",
    desc: "A contemporary housing development shaped around private living, landscaped open spaces and family-oriented amenities.",
    desc2: "Rowhouse Community is a contemporary housing development designed around private living, landscaped open spaces and family-oriented amenities. Clean geometric façades, balconies, shaded outdoor areas, gardens and dedicated play zones create a balanced residential environment with a strong focus on community and everyday comfort.",
    featured: true,
    scene: "s3",
    sceneB: "s5",
    mainImageUrl: "/project-images/rowhouse-community/entry-gate.webp",
    secondaryImageUrl: "/project-images/rowhouse-community/garden-01.webp",
    tertiaryImageUrl: "/project-images/rowhouse-community/garden-02.webp",
    quaternaryImageUrl: "/project-images/rowhouse-community/garden-03.webp",
    additionalImageUrls: ["/project-images/rowhouse-community/play-area.webp"],
    imageAlt: "Contemporary rowhouse community entrance with clean geometric façades and landscaped edges",
    align: "right",
    span: "wide",
  },
  {
    slug: "private-residence-2",
    order: 3,
    no: "04",
    name: "Private Residence 2",
    location: "Pune, India",
    year: "2025",
    category: "Residential Interior Design",
    architect: "Rishit Shah",
    typology: "Residential",
    discipline: "Interior",
    status: "Completed",
    size: "Private residence",
    desc: "A refined contemporary home defined by soft neutral tones, natural textures and understated luxury.",
    desc2: "Residence 02 is a refined contemporary home defined by soft neutral tones, natural textures and understated luxury. The interiors combine warm wood, marble, textured wall panels and subtle metallic accents, with sculptural lighting and illuminated stone features adding depth. An open living and dining layout creates a seamless, spacious environment while maintaining a calm and elegant character throughout.",
    featured: true,
    scene: "s4",
    sceneB: "s6",
    mainImageUrl: "/project-images/private-residence-2/view-01.webp",
    secondaryImageUrl: "/project-images/private-residence-2/view-02.webp",
    tertiaryImageUrl: "/project-images/private-residence-2/view-03.webp",
    quaternaryImageUrl: "/project-images/private-residence-2/view-04.webp",
    imageAlt: "Refined contemporary living and dining interior in soft neutral tones",
    align: "left",
    span: "wide",
  },
  {
    slug: "krushna-kunj",
    order: 4,
    no: "05",
    name: "Krushna Kunj",
    location: "Pune, India",
    year: "2025",
    category: "Residential Architecture",
    architect: "Ketaki",
    developer: "Devraj Group",
    typology: "Residential",
    discipline: "Exterior",
    status: "Completed",
    size: "Residential development",
    desc: "A contemporary residential building articulated by a crisp white frame, warm terracotta recesses and deeply shaded balconies.",
    desc2: "Krushna Kunj is a contemporary residential development defined by a disciplined geometric façade and a warm, restrained material palette. Deep-set balconies, terracotta-toned recesses and slender metal railings create rhythm and shade, while planted upper terraces and generous outdoor spaces soften the compact urban form.",
    featured: true,
    scene: "s1",
    sceneB: "s5",
    mainImageUrl: "/project-images/krushna-kunj/angular.webp",
    secondaryImageUrl: "/project-images/krushna-kunj/front.webp",
    tertiaryImageUrl: "/project-images/krushna-kunj/balcony.webp",
    imageAlt: "Angular view of Krushna Kunj with white framed façades and terracotta balcony recesses",
    align: "right",
    span: "tall",
  },
  {
    slug: "arkscape",
    order: 5,
    no: "06",
    name: "ArkScape",
    location: "Pune, India",
    year: "2025",
    category: "Residential Architecture",
    architect: "Rohit Kawade",
    typology: "Residential",
    discipline: "Exterior",
    status: "Completed",
    size: "Urban residence",
    desc: "A refined urban residence balancing classical proportions with clean contemporary detailing and planted outdoor spaces.",
    desc2: "ArkScape combines a composed, symmetrical street presence with deep balconies, tall glazing and carefully integrated planting. Subtle mouldings and a warm neutral palette lend the façade a timeless character, while generous openings and rooftop terraces bring light, greenery and openness into the compact urban residence.",
    featured: true,
    scene: "s5",
    sceneB: "s3",
    mainImageUrl: "/project-images/arkscape/angular.webp",
    secondaryImageUrl: "/project-images/arkscape/front.webp",
    imageAlt: "Angular view of ArkScape with planted balconies, classical proportions and a warm neutral façade",
    align: "right",
    span: "tall",
  },
  {
    slug: "private-residence-3",
    order: 6,
    no: "07",
    name: "Private Residence 3",
    location: "Pune, India",
    year: "2026",
    category: "Residential Interior Design",
    architect: "The Rouge Wall",
    typology: "Residential",
    discipline: "Interior",
    status: "Completed",
    size: "Private residence",
    desc: "A warm contemporary home where soft ivory surfaces, sculpted curves and dark timber are layered with brass accents and ambient light.",
    desc2: "Private Residence 3 balances understated luxury with a relaxed domestic character. Curved openings and furniture soften the open living and dining spaces, while fluted panelling, crafted timber, brass screens and illuminated niches add rhythm and depth. A restrained neutral palette allows artwork, textured finishes and sculptural lighting to give each space its own identity while maintaining a calm, cohesive whole.",
    featured: true,
    scene: "s4",
    sceneB: "s2",
    mainImageUrl: "/project-images/private-residence-3/living-room.jpg",
    secondaryImageUrl: "/project-images/private-residence-3/dining-room.jpg",
    tertiaryImageUrl: "/project-images/private-residence-3/tv-wall.jpg",
    quaternaryImageUrl: "/project-images/private-residence-3/study.jpg",
    additionalImageUrls: [
      "/project-images/private-residence-3/partition-detail.jpg",
      "/project-images/private-residence-3/tv-detail.jpg",
    ],
    imageAlt: "Warm contemporary living room with curved furniture, ivory panelling, dark timber and brass accents",
    align: "left",
    span: "wide",
  },
  {
    slug: "private-residence-4",
    order: 7,
    no: "08",
    name: "Private Residence 4",
    location: "Pune, India",
    year: "2026",
    category: "Residential Interior Design",
    architect: "Atelier's Design",
    typology: "Residential",
    discipline: "Interior",
    status: "Completed",
    size: "Private residence",
    desc: "A collection of expressive bedrooms shaped by tactile surfaces, deep colour, sculptural lighting and finely detailed contemporary joinery.",
    desc2: "Private Residence 4 explores three distinct bedroom identities within a cohesive contemporary language. Rich timber, smoked glass and layered wall treatments create depth, while deep green, cocoa and muted rose accents give each room an individual mood. Rounded furniture, bespoke storage and warm indirect lighting balance the strong material character with softness and residential comfort.",
    featured: true,
    scene: "s3",
    sceneB: "s6",
    mainImageUrl: "/project-images/private-residence-4/green-bedroom.jpg",
    secondaryImageUrl: "/project-images/private-residence-4/rose-bedroom.jpg",
    tertiaryImageUrl: "/project-images/private-residence-4/dark-bedroom.jpg",
    imageAlt: "Contemporary bedroom in Pune with deep green textiles, textured terracotta wall and dark glazed wardrobes",
    align: "right",
    span: "tall",
  },
  {
    no: "04",
    name: "Monolith Tower",
    location: "Dubai, AE",
    year: "2026",
    category: "Supertall · Mixed-Use",
    architect: "Atelier Kfield",
    typology: "Mixed-Use",
    status: "In Progress",
    size: "164,000 m²",
    desc: "A single fold of concrete and glass rising from the desert floor — a vertical city carved as one continuous gesture of light.",
    desc2: "Atelier Kfield designed Monolith to read as one uninterrupted surface from the highway, dissolving into terraces as you approach. Space Scape produced the exterior and aerial imagery — a full light study from dawn haze to blue hour — to present the design before ground was broken.",
    featured: true,
    scene: "s1",
    sceneB: "s4",
    align: "left",
    span: "tall",
  },
  {
    no: "05",
    name: "Glass Pavilion",
    location: "Reykjavík, IS",
    year: "2025",
    category: "Cultural · Exhibition",
    architect: "Brønd Studio",
    typology: "Cultural",
    status: "Completed",
    size: "9,400 m²",
    desc: "Walls dissolve into the landscape. The building exists only as a frame for the moving northern light passing through it.",
    desc2: "Brønd Studio asked for a building that disappears. We answered with imagery that follows the light rather than the structure — long exposures of aurora across the glass, interiors lit only by what the sky gives. Shot across a single Arctic night.",
    featured: false,
    scene: "s4",
    sceneB: "s2",
    align: "right",
    span: "std",
  },
  {
    no: "06",
    name: "The Cantilever",
    location: "Big Sur, US",
    year: "2025",
    category: "Residential · Private",
    architect: "Hale Office",
    typology: "Residential",
    status: "Completed",
    size: "1,200 m²",
    desc: "A house held in mid-air over the Pacific — a horizontal line drawn against the horizon, anchored only by shadow.",
    desc2: "Everything about the image had to feel weightless. We placed the camera below the deck to let Hale Office's cantilever read against open sky, and graded the whole sequence to the ten minutes before the sun lets go of the water.",
    featured: true,
    scene: "s3",
    sceneB: "s5",
    align: "full",
    span: "wide",
  },
  {
    no: "07",
    name: "Concrete Cathedral",
    location: "Lisbon, PT",
    year: "2024",
    category: "Civic · Sacred",
    architect: "Praxis Arquitectos",
    typology: "Civic",
    status: "Completed",
    size: "21,000 m²",
    desc: "Light falls five storeys before it touches the floor. Mass becomes weightless in the silence of the volume.",
    desc2: "The drama is entirely in Praxis Arquitectos' section. We modelled the path of a single shaft of light through the day and built the interior imagery around the one minute it reaches the altar — mass dissolving into atmosphere.",
    featured: false,
    scene: "s2",
    sceneB: "s6",
    align: "left",
    span: "std",
  },
  {
    no: "08",
    name: "Vertical Garden",
    location: "Singapore, SG",
    year: "2026",
    category: "Mixed-Use · Tower",
    architect: "Ng + Lin",
    typology: "Mixed-Use",
    status: "In Progress",
    size: "88,000 m²",
    desc: "A tower that wears its landscape on the outside — thirty floors of terraced green spilling toward the street.",
    desc2: "The challenge was making Ng + Lin's planting feel inevitable rather than decorative. We grew the vegetation digitally across thirty levels and lit it in tropical afternoon haze, so the green reads as the building's primary material.",
    featured: true,
    scene: "s5",
    sceneB: "s1",
    align: "right",
    span: "tall",
  },
  {
    no: "09",
    name: "Desert Observatory",
    location: "AlUla, SA",
    year: "2027",
    category: "Cultural · Research",
    architect: "Studio Hejaz",
    typology: "Cultural",
    status: "Concept",
    size: "14,500 m²",
    desc: "Sandstone and shade engineered for forty degrees, opening to the sky at the exact hour the heat finally breaks.",
    desc2: "A concept piece for Studio Hejaz, carried entirely by imagery. We rendered the observatory at three moments — blistering noon, the break of dusk, and a clear desert night — to argue the architecture through light and shadow alone.",
    featured: false,
    scene: "s6",
    sceneB: "s3",
    align: "full",
    span: "std",
  },
];

// Keep the commissioned portfolio selection explicit so placeholder entries
// never generate public cards or project routes.
export const PROJECTS: Project[] = PROJECT_CATALOG.slice(0, 8);

export const projectSlug = (project: Project) =>
  project.slug || project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export const getProjectBySlug = (slug: string) =>
  PROJECTS.find((project) => projectSlug(project) === slug);
