export const projectsQuery = `*[_type == "project"] | order(order asc, year desc) {
  "no": coalesce(number, string(order + 1)),
  name,
  "slug": slug.current,
  order,
  location,
  year,
  category,
  architect,
  developer,
  typology,
  discipline,
  status,
  size,
  "desc": summary,
  "desc2": description,
  featured,
  "mainImageUrl": mainImage.asset->url,
  "secondaryImageUrl": secondaryImage.asset->url,
  "tertiaryImageUrl": tertiaryImage.asset->url,
  "quaternaryImageUrl": quaternaryImage.asset->url,
  "additionalImageUrls": additionalImages[].asset->url,
  "imageAlt": coalesce(mainImage.alt, name),
  align,
  span
}`;
